/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ues21.cansat21.vista;

import edu.ues21.cansat21.control.Controlador;
import edu.ues21.cansat21.modelo.ArchivoSeleccionado;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.dnd.DropTarget;
import java.io.File;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.TransferHandler;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.icons.google_material_design_icons.GoogleMaterialDesignIcons;
import jiconfont.swing.IconFontSwing;

/**
 *
 * @author agustin
 */
public class Principal extends javax.swing.JFrame implements InterfazVista {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane = new javax.swing.JSplitPane();
        panelIzquierda = new javax.swing.JPanel();
        jButtonTemp = new javax.swing.JButton();
        jButtonHumedad = new javax.swing.JButton();
        jButtonPresion = new javax.swing.JButton();
        jButtonSelArchivo = new javax.swing.JButton();
        lblArchivoSeleccionado = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblAmburguesa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(11, 0), new java.awt.Dimension(11, 0), new java.awt.Dimension(11, 32767));
        cmbArchivosSel = new javax.swing.JComboBox<>();
        jButtonQuitarArchSel = new javax.swing.JButton();
        jButtonIncliAcel = new javax.swing.JButton();
        jButtonRotaGiro = new javax.swing.JButton();
        panelDerecha = new javax.swing.JPanel();
        panelTile1 = new javax.swing.JPanel();
        panelTile2 = new javax.swing.JPanel();
        panelTile3 = new javax.swing.JPanel();
        panelTile4 = new javax.swing.JPanel();
        panelTile5 = new javax.swing.JPanel();
        panelTile6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CANSAT ESTACION TERRENA");
        setBackground(new java.awt.Color(254, 254, 254));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconos/satelliteantenna.png")));
        setMinimumSize(new java.awt.Dimension(800, 600));

        jSplitPane.setBackground(new java.awt.Color(254, 254, 254));
        jSplitPane.setDividerLocation(200);
        jSplitPane.setDividerSize(5);
        jSplitPane.setPreferredSize(new java.awt.Dimension(800, 600));

        panelIzquierda.setBackground(new java.awt.Color(137, 196, 244));

        jButtonTemp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonTemp.setForeground(new java.awt.Color(130, 130, 130));
        jButtonTemp.setText("Temperatura");
        jButtonTemp.setActionCommand("TemperaturaGrafico");
        jButtonTemp.setPreferredSize(new java.awt.Dimension(70, 30));
        jButtonTemp.setRolloverEnabled(true);
        //String path = this.getClass().getResource("/iconos/icono-temperatura.gif").toString();
        ////InputStream is = this.getClass().getResourceAsStream("/iconos/icono-temperatura.gif");//para árbol
        //
        //ImageIcon animatedGif = new ImageIcon(path);
        //jButtonTemp.setRolloverIcon(animatedGif);
        //animatedGif.getImage().flush();
        Icon iconTemp = IconFontSwing.buildIcon(FontAwesome.THERMOMETER_HALF, 18, new Color(130, 130, 130));
        jButtonTemp.setIcon(iconTemp);

        jButtonHumedad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonHumedad.setForeground(new java.awt.Color(130, 130, 130));
        jButtonHumedad.setText("Humedad");
        jButtonHumedad.setActionCommand("HumedadGrafico");
        jButtonHumedad.setPreferredSize(new java.awt.Dimension(70, 30));
        Icon iconHumedad = IconFontSwing.buildIcon(FontAwesome.CLOUD, 18, new Color(130, 130, 130));
        jButtonHumedad.setIcon(iconHumedad);

        jButtonPresion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPresion.setForeground(new java.awt.Color(130, 130, 130));
        jButtonPresion.setText("Presión");
        jButtonPresion.setActionCommand("PresionGrafico");
        jButtonPresion.setPreferredSize(new java.awt.Dimension(70, 30));
        Icon iconPresion = IconFontSwing.buildIcon(FontAwesome.TACHOMETER, 18, new Color(130, 130, 130));
        jButtonPresion.setIcon(iconPresion);

        jButtonSelArchivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonSelArchivo.setForeground(new java.awt.Color(130, 130, 130));
        jButtonSelArchivo.setToolTipText("Seleccione archivos...");
        jButtonSelArchivo.setActionCommand("ELEGIR_CSV_ACCION");
        Icon iconArchivo = IconFontSwing.buildIcon(FontAwesome.FILE, 14, new Color(130, 130, 130));
        jButtonSelArchivo.setIcon(iconArchivo);

        lblArchivoSeleccionado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblArchivoSeleccionado.setForeground(new java.awt.Color(130, 130, 130));

        panelMenu.setBackground(new java.awt.Color(54, 100, 194));
        panelMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelMenu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        panelMenu.setLayout(new java.awt.GridBagLayout());

        lblAmburguesa.setBackground(new java.awt.Color(54, 100, 194));
        lblAmburguesa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblAmburguesa.setForeground(new java.awt.Color(255, 255, 255));
        Icon icon = IconFontSwing.buildIcon(GoogleMaterialDesignIcons.MENU, 18, new Color(255, 255, 255));
        lblAmburguesa.setIcon(icon);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelMenu.add(lblAmburguesa, gridBagConstraints);
        lblAmburguesa.getAccessibleContext().setAccessibleName("lblAmburguesa");

        jLabel1.setBackground(new java.awt.Color(54, 100, 194));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");
        jLabel1.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelMenu.add(jLabel1, gridBagConstraints);
        panelMenu.add(filler1, new java.awt.GridBagConstraints());

        jButtonQuitarArchSel.setToolTipText("Quitar el archivo seleccionado");
        jButtonQuitarArchSel.setActionCommand("BORRAR_ARCH_SEL_ACCION");
        Icon iconQuitarArchivo = IconFontSwing.buildIcon(FontAwesome.TRASH, 14, new Color(130, 130, 130));
        jButtonQuitarArchSel.setIcon(iconQuitarArchivo);

        jButtonIncliAcel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonIncliAcel.setForeground(new java.awt.Color(130, 130, 130));
        jButtonIncliAcel.setText("Inclinación (Acel)");
        jButtonIncliAcel.setActionCommand("AcelerometroGrafico");
        jButtonIncliAcel.setPreferredSize(new java.awt.Dimension(70, 30));
        Icon iconIncliAcel = IconFontSwing.buildIcon(FontAwesome.COMPASS, 18, new Color(130, 130, 130));
        jButtonIncliAcel.setIcon(iconIncliAcel);

        jButtonRotaGiro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonRotaGiro.setForeground(new java.awt.Color(130, 130, 130));
        jButtonRotaGiro.setText("Rotación (Giro)");
        jButtonRotaGiro.setActionCommand("GiroscopoGrafico");
        jButtonRotaGiro.setPreferredSize(new java.awt.Dimension(70, 30));
        Icon iconRotaGiro = IconFontSwing.buildIcon(FontAwesome.RAVELRY, 18, new Color(130, 130, 130));
        jButtonRotaGiro.setIcon(iconRotaGiro);

        javax.swing.GroupLayout panelIzquierdaLayout = new javax.swing.GroupLayout(panelIzquierda);
        panelIzquierda.setLayout(panelIzquierdaLayout);
        panelIzquierdaLayout.setHorizontalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIzquierdaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblArchivoSeleccionado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzquierdaLayout.createSequentialGroup()
                        .addComponent(jButtonSelArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbArchivosSel, 0, 106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonQuitarArchSel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHumedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPresion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIncliAcel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRotaGiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelIzquierdaLayout.setVerticalGroup(
            panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzquierdaLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIzquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbArchivosSel)
                    .addComponent(jButtonQuitarArchSel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArchivoSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSelArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHumedad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPresion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIncliAcel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRotaGiro, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jSplitPane.setLeftComponent(panelIzquierda);

        panelDerecha.setBackground(new java.awt.Color(254, 254, 254));
        panelDerecha.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        panelTile1.setLayout(new java.awt.BorderLayout());
        panelDerecha.add(panelTile1);
        //panelTile1.setDropTarget(new DropTarget() {
            //                    @Override
            //                    public synchronized void drop(DropTargetDropEvent evt) {
                //                        panelTile1.add(new JLabel("BOTON ARRASTRADO"));
                //                        panelTile1.revalidate();
                //                        panelTile1.repaint();
                //                    }
            //                });

    panelTile2.setLayout(new java.awt.BorderLayout());
    panelDerecha.add(panelTile2);

    panelTile3.setLayout(new java.awt.BorderLayout());
    panelDerecha.add(panelTile3);

    panelTile4.setLayout(new java.awt.BorderLayout());
    panelDerecha.add(panelTile4);

    panelTile5.setLayout(new java.awt.BorderLayout());
    panelDerecha.add(panelTile5);

    panelTile6.setLayout(new java.awt.BorderLayout());
    panelDerecha.add(panelTile6);

    jSplitPane.setRightComponent(panelDerecha);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ArchivoSeleccionado> cmbArchivosSel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonHumedad;
    private javax.swing.JButton jButtonIncliAcel;
    private javax.swing.JButton jButtonPresion;
    private javax.swing.JButton jButtonQuitarArchSel;
    private javax.swing.JButton jButtonRotaGiro;
    private javax.swing.JButton jButtonSelArchivo;
    private javax.swing.JButton jButtonTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel lblAmburguesa;
    private javax.swing.JLabel lblArchivoSeleccionado;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPanel panelMenu;
    public javax.swing.JPanel panelTile1;
    public javax.swing.JPanel panelTile2;
    public javax.swing.JPanel panelTile3;
    public javax.swing.JPanel panelTile4;
    public javax.swing.JPanel panelTile5;
    public javax.swing.JPanel panelTile6;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(Controlador c) {
        for (Component component : this.panelIzquierda.getComponents()) {
            if (component instanceof JButton) {
                if (((JButton) component).getActionCommand().contains("ACCION")) {
                    ((JButton) component).addActionListener(c);
                } else {
                    ((JButton) component).setTransferHandler(new TransferHandler("icon"));
                    ((JButton) component).addMouseMotionListener(c);
                }
            }
        }
        for (Component component : this.panelMenu.getComponents()) {
            if (component instanceof JLabel) {
                if (component.getAccessibleContext().getAccessibleName().equals("lblAmburguesa")) {
                    ((JLabel) component).addMouseListener(c);
                }
            }
        }
        for (Component component : this.panelDerecha.getComponents()) {
            if (component instanceof JPanel) {
                ((JPanel) component).setDropTarget(new DropTarget(component, c));
            }
        }
        this.addWindowListener(c);
    }

    @Override
    public void iniciaVista() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    @Override
    public void imprimeMensaje(Exception... e) {
        if (e.length > 0) {
            JOptionPane.showMessageDialog(this, "Error: " + e[0].getMessage(), "Información", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Operación ejecutada con exito", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    @Override
    public File[] seleccionarArchivos() {
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Seleccione 1 o más archivo del CANSAT");
        jfc.setMultiSelectionEnabled(true);
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo CSV", "CSV");
        jfc.addChoosableFileFilter(filter);
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
//            lblArchivoSeleccionado.setText(jfc.getSelectedFile().getPath().substring(jfc.getSelectedFile().getPath().lastIndexOf(System.getProperty("file.separator"))));
//            lblArchivoSeleccionado.setToolTipText(jfc.getSelectedFile().getPath());
            return jfc.getSelectedFiles();
        }
        return null;
    }

    @Override
    public void limpiaVista() {
        lblArchivoSeleccionado.setText("");
        lblArchivoSeleccionado.setToolTipText(null);
    }

    @Override
    public void cargarComboArchivosSel(ArchivoSeleccionado archivosSel) {
        cmbArchivosSel.addItem(archivosSel);
    }

    @Override
    public void quitarItemComboArchivoSel() {
        int idx = cmbArchivosSel.getSelectedIndex();
        if (idx > -1) {
            cmbArchivosSel.removeItemAt(idx);
        }
        cmbArchivosSel.revalidate();
        cmbArchivosSel.repaint();
    }

    @Override
    public String pathArchivoSeleccionado() {
        ArchivoSeleccionado archivo = (ArchivoSeleccionado) cmbArchivosSel.getSelectedItem();
        return archivo != null ? archivo.getPathArchivo() : null;
    }

    @Override
    public void cierraSplitPane(int posicion) {
        jSplitPane.setDividerLocation(posicion);
    }
    
    @Override
    public void cierraSistema(){
        if (JOptionPane.showConfirmDialog(null, 
            "¿Seguro desea salir?", "Información", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }

}
